app = "plex-metatube-server-001"
primary_region = "tyo"

[build]
  image = "ghcr.io/metatube/metatube-server:latest"

[env]
  PLEX_TOKEN = "PLEX15"
  CRON_UPDATE = "true"
  UPDATE_INTERVAL = "7200"
  GHCR_USER = "w9a08qw1-hue"


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
