app = "plex-metatube-server-001"  # 유니크하게 바꿔도 됨
primary_region = "tyo"            # Tokyo 리전

[env]
PLEX_TOKEN = "PLEX15"
CRON_UPDATE = "true"
UPDATE_INTERVAL = "7200"
GHCR_USER = "<GitHub 사용자명>"
GHCR_TOKEN = "<생성한 PAT 값>"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    handlers = ["http"]
